# These are supported funding model platforms

github: VelvetThePanda # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: VelvetThePanda # Replace with a single Patreon username
ko_fi: VelvetThePanda # Replace with a single Ko-fi username
