<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>a23d9d17-28f4-449a-8405-a37c4439580d</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="EFCore.NamingConventions" Version="9.0.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.6" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.6">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.6" />
      <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.6" />
      <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="9.0.6" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
      <PackageReference Include="Remora.Results" Version="8.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Kobalt\Kobalt.Shared\Kobalt.Shared.csproj" />
    </ItemGroup>

</Project>
