// <auto-generated />
using System;
using Kobalt.Phishing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kobalt.Phishing.Data.Migrations
{
    [DbContext(typeof(PhishingContext))]
    partial class PhishingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("kobalt_phishing")
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kobalt.Phishing.Data.Entities.SuspiciousAvatar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<decimal>("AddedBy")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("added_by");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<decimal?>("GuildID")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<string>("Md5Hash")
                        .HasColumnType("text")
                        .HasColumnName("md5hash");

                    b.Property<byte[]>("Phash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("phash");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_suspicious_avatars");

                    b.ToTable("suspicious_avatars", "kobalt_phishing");
                });

            modelBuilder.Entity("Kobalt.Phishing.Data.Entities.SuspiciousUsername", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CreatedBy")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("created_by");

                    b.Property<decimal?>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<int>("ParseType")
                        .HasColumnType("integer")
                        .HasColumnName("parse_type");

                    b.Property<string>("UsernamePattern")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username_pattern");

                    b.HasKey("Id")
                        .HasName("pk_suspicious_usernames");

                    b.ToTable("suspicious_usernames", "kobalt_phishing");
                });
#pragma warning restore 612, 618
        }
    }
}
