// <auto-generated />
using System;
using Kobalt.Plugins.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kobalt.Plugins.Core.Data.Migrations
{
    [DbContext(typeof(KobaltContext))]
    [Migration("20230522091616_AddAntiPhishing")]
    partial class AddAntiPhishing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("kobalt_core")
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kobalt.Plugins.Core.Data.Entities.Guild", b =>
                {
                    b.Property<ulong>("ID")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("id");

                    b.HasKey("ID")
                        .HasName("pk_guilds");

                    b.ToTable("guilds", "kobalt_core");
                });

            modelBuilder.Entity("Kobalt.Plugins.Core.Data.Entities.GuildAntiRaidConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountFlagsBypass")
                        .HasColumnType("integer")
                        .HasColumnName("account_flags_bypass");

                    b.Property<TimeSpan>("AntiRaidCooldownPeriod")
                        .HasColumnType("interval")
                        .HasColumnName("anti_raid_cooldown_period");

                    b.Property<int>("BaseJoinScore")
                        .HasColumnType("integer")
                        .HasColumnName("base_join_score");

                    b.Property<ulong>("GuildID")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<int>("JoinVelocityScore")
                        .HasColumnType("integer")
                        .HasColumnName("join_velocity_score");

                    b.Property<TimeSpan>("LastJoinBufferPeriod")
                        .HasColumnType("interval")
                        .HasColumnName("last_join_buffer_period");

                    b.Property<TimeSpan>("MinimumAccountAge")
                        .HasColumnType("interval")
                        .HasColumnName("minimum_account_age");

                    b.Property<int>("MinimumAgeScore")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_age_score");

                    b.Property<TimeSpan?>("MiniumAccountAgeBypass")
                        .HasColumnType("interval")
                        .HasColumnName("minium_account_age_bypass");

                    b.Property<int>("NoAvatarScore")
                        .HasColumnType("integer")
                        .HasColumnName("no_avatar_score");

                    b.Property<int>("SuspiciousInviteScore")
                        .HasColumnType("integer")
                        .HasColumnName("suspicious_invite_score");

                    b.Property<int>("ThreatScoreThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("threat_score_threshold");

                    b.HasKey("Id")
                        .HasName("pk_guild_anti_raid_config");

                    b.HasIndex("GuildID")
                        .IsUnique()
                        .HasDatabaseName("ix_guild_anti_raid_config_guild_id");

                    b.ToTable("guild_anti_raid_config", "kobalt_core");
                });

            modelBuilder.Entity("Kobalt.Plugins.Core.Data.Entities.GuildAutoModConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<ulong>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<int?>("PushToTalkThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("push_to_talk_threshold");

                    b.HasKey("Id")
                        .HasName("pk_guild_auto_mod_config");

                    b.HasIndex("GuildId")
                        .IsUnique()
                        .HasDatabaseName("ix_guild_auto_mod_config_guild_id");

                    b.ToTable("guild_auto_mod_config", "kobalt_core");
                });

            modelBuilder.Entity("Kobalt.Plugins.Core.Data.Entities.GuildPhishingConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DetectionAction")
                        .HasColumnType("integer")
                        .HasColumnName("detection_action");

                    b.Property<ulong>("GuildID")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<bool>("ScanLinks")
                        .HasColumnType("boolean")
                        .HasColumnName("scan_links");

                    b.Property<bool>("ScanUsers")
                        .HasColumnType("boolean")
                        .HasColumnName("scan_users");

                    b.HasKey("Id")
                        .HasName("pk_guild_phishing_config");

                    b.HasIndex("GuildID")
                        .IsUnique()
                        .HasDatabaseName("ix_guild_phishing_config_guild_id");

                    b.ToTable("guild_phishing_config", "kobalt_core");
                });

            modelBuilder.Entity("Kobalt.Plugins.Core.Data.Entities.GuildUserJoiner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<ulong>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<ulong>("UserId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_guild_user_joiner");

                    b.HasIndex("GuildId")
                        .HasDatabaseName("ix_guild_user_joiner_guild_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_guild_user_joiner_user_id");

                    b.ToTable("guild_user_joiner", "kobalt_core");
                });

            modelBuilder.Entity("Kobalt.Plugins.Core.Data.Entities.LogChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<ulong>("ChannelID")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("channel_id");

                    b.Property<ulong>("GuildID")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<decimal>("Type")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("type");

                    b.Property<ulong?>("WebhookID")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("webhook_id");

                    b.Property<string>("WebhookToken")
                        .HasColumnType("text")
                        .HasColumnName("webhook_token");

                    b.HasKey("Id")
                        .HasName("pk_log_channels");

                    b.HasIndex("GuildID")
                        .HasDatabaseName("ix_log_channels_guild_id");

                    b.ToTable("log_channels", "kobalt_core");
                });

            modelBuilder.Entity("Kobalt.Plugins.Core.Data.Entities.User", b =>
                {
                    b.Property<ulong>("ID")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("id");

                    b.Property<bool>("DisplayTimezone")
                        .HasColumnType("boolean")
                        .HasColumnName("display_timezone");

                    b.Property<string>("Timezone")
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.HasKey("ID")
                        .HasName("pk_users");

                    b.ToTable("users", "kobalt_core");
                });

            modelBuilder.Entity("Kobalt.Plugins.Core.Data.Entities.GuildAntiRaidConfig", b =>
                {
                    b.HasOne("Kobalt.Plugins.Core.Data.Entities.Guild", "Guild")
                        .WithOne("AntiRaidConfig")
                        .HasForeignKey("Kobalt.Plugins.Core.Data.Entities.GuildAntiRaidConfig", "GuildID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guild_anti_raid_config_guilds_guild_id");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Kobalt.Plugins.Core.Data.Entities.GuildAutoModConfig", b =>
                {
                    b.HasOne("Kobalt.Plugins.Core.Data.Entities.Guild", "Guild")
                        .WithOne("AutoModConfig")
                        .HasForeignKey("Kobalt.Plugins.Core.Data.Entities.GuildAutoModConfig", "GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guild_auto_mod_config_guilds_guild_id");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Kobalt.Plugins.Core.Data.Entities.GuildPhishingConfig", b =>
                {
                    b.HasOne("Kobalt.Plugins.Core.Data.Entities.Guild", "Guild")
                        .WithOne("PhishingConfig")
                        .HasForeignKey("Kobalt.Plugins.Core.Data.Entities.GuildPhishingConfig", "GuildID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guild_phishing_config_guilds_guild_id");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Kobalt.Plugins.Core.Data.Entities.GuildUserJoiner", b =>
                {
                    b.HasOne("Kobalt.Plugins.Core.Data.Entities.Guild", "Guild")
                        .WithMany("Users")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guild_user_joiner_guilds_guild_id");

                    b.HasOne("Kobalt.Plugins.Core.Data.Entities.User", "User")
                        .WithMany("Guilds")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guild_user_joiner_users_user_id");

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kobalt.Plugins.Core.Data.Entities.LogChannel", b =>
                {
                    b.HasOne("Kobalt.Plugins.Core.Data.Entities.Guild", null)
                        .WithMany("LogChannels")
                        .HasForeignKey("GuildID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_log_channels_guilds_guild_id");
                });

            modelBuilder.Entity("Kobalt.Plugins.Core.Data.Entities.Guild", b =>
                {
                    b.Navigation("AntiRaidConfig")
                        .IsRequired();

                    b.Navigation("AutoModConfig")
                        .IsRequired();

                    b.Navigation("LogChannels");

                    b.Navigation("PhishingConfig")
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Kobalt.Plugins.Core.Data.Entities.User", b =>
                {
                    b.Navigation("Guilds");
                });
#pragma warning restore 612, 618
        }
    }
}
